### ISSUE TITLE
Change the method to access the menu

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#1002]
- [ ] Show the menu when we press any directional button on the remote control 
- [ ] Add burger menu button to access the menu

**Comment by FirasTelmoudi** [comment]
Why don't fix the real issues with this app
Like the screen most of the rimes gets stuck on "Adhan"
Or the announcement ticker doesn't display any test with flash info
I'm seriously starting to look for an alternative

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> Why don't fix the real issues with this app Like the screen most of the rimes gets stuck on "Adhan" Or the announcement ticker doesn't display any test with flash info I'm seriously starting to look for an alternative

السلام عليكم و رحمة الله و بركاته 
Brother, witch version are you using ?

**Comment by FirasTelmoudi** [comment]
The latest one 1.8.2

**Comment by ibrahim-zehhaf-mawaqit** [comment]
This issue has been resolved and no mosque is facing it now.
Please remove the app and install it again or clear the cache of the app.

BTW answering assalam is important in Islam.

**Comment by FirasTelmoudi** [comment]
وعليكم السلام ورحمة الله وبركاته
I know that brother
The last time i pushed a flash announcement it was there on the TV displayed at the bottom ticker but when i pushed another one last week the issue is there again
I believe it's server sided issue
And the Adhan stuck on the TV did you resolve that as well?
And please add a night mode where we can let the TV on all night with black screen like during the Iqama
Please respond to me about these issues and request
بارك الله فيكم وجزاكم الله خير الجزاء
في عون الله

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Your initial request was a bit aggressive, we didn't appreciate it. There are slightly more respectful expressions for asking or pointing out things.

But elhadulillah your last message is fine, so I suggest you to create an issue on github for all your requests with more context and description, thank you. 

- [ ] Flash message
- [ ] Night mode (we will work on this issue https://github.com/mawaqit/android-tv-app/issues/943)
- [ ] Adhan stuck is already fixed, are you always facing it ?

**Comment by FirasTelmoudi** [comment]
Nor ignoring people is not appreciated... So you know where this is coming from, i'm trying to help my local mosques and i'm pretty sure that you have an idea how mosques staff would be when they say that the Adhan stuck and the announcement doesn't appears on the TV bottom ticker
I try to help my local muslim community and i hear is criticize 
I posted the issues for more than a month on #970 #971 and #972
And i didn't get any reply from you guys assuming that you have a busy life as i do
But when i saw your pull request about a silly idea like press button for menu... that made me furious
I'll try to clean install the app for 4 mosques and see if the issues still there
Until then i hope you don't ignore my posts and last but not least
جازاكم الله خيرا وعضم اجركم وغفر ذنبكم

**Comment by ibrahim-zehhaf-mawaqit** [comment]
We didn't ignore you brother, we prioritize issues against many criteria, and we are volunteers most of us with little time.
Your issues have never been reported by other users. maybe it's related to your box or smart tv.
You can buy our box to have the best experience and best compatibility, if you want, but waiting for your feedback after reinstalling the app.

Insh'Allah will check your issues, please add the mosque ID to help us reproduce the bug.
Please kindly stop discussing here and move the discussion to the issues you created.

**Comment by FirasTelmoudi** [comment]
Salam alaykom
Can we DM brother, the issues still there and you need to help me... i'll send you some vidoes and photos of the issues
